<a href="https://colab.research.google.com/github/abhinavmarkanda/UCS547-Accelerated-Data-Science/blob/main/Assignment1(UCS547).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)


[5 4 6 3 2 1]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comparison = arr1 == arr2
print(comparison)

print(np.array_equal(arr1, arr2))

[[ True  True]
 [ True  True]]
True


In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)
most_freq = values[np.argmax(counts)]
indices = np.where(x == most_freq)

print("Most frequent value:", most_freq)
print("Indices:", indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_freq = values[np.argmax(counts)]
indices = np.where(y == most_freq)

print("Most frequent value:", most_freq)
print("Indices:", indices)

Most frequent value: 1
Indices: (array([0, 5, 7, 8, 9]),)
Most frequent value: 1
Indices: (array([0, 1, 2]),)


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum = np.sum(gfg)
print(total_sum)

45


In [ ]:
row_sum = np.sum(gfg, axis=1)
print(row_sum)

col_sum = np.sum(gfg, axis=0)
print(col_sum)

[[14]
 [16]
 [15]]
[[20  9 16]]
